### ISSUE TITLE
Add xdebug

### ISSUE THREAD

**Issue by jlyon** [terra-ops/docker-drupal#4]
Not sure if this is absolutely appropriate, but bundling xdebug and xhprof would streamline local dev work.

**Comment by jonpugh** [comment]
I think you are right, but we probably would want to keep a separate "development" app container.

We wouldn't want to override this for the entire app, either...  I'm thinking we should add some kind of environment-specific docker-compose overrides here, like so:

```
docker-compose:
  environment-overrides:
    # This would only override the docker compose for an environment named "dev"
    dev:
      app:
        image: terra/drupal-dev
```

What do you think, @jlyon ?
